### ISSUE TITLE
How applying the model to a different language

### ISSUE THREAD

**Issue by chontipan** [neulab/incremental_tree_edit#2]
Hi authors, your work is interesting. May I ask steps of applying this model to a different language (i.e., JavaScript)?
1. Create ASDL grammar on tranX?
2. Convert raw data (source code) to the ginhubedit dataset format?
3. Make edit sequence generation (could you please suggest how to do?)

```
Data Preprocessing and Sanity Check
Todo: when applying the model to a different programming language, how to check/debug the ASDL grammar implementation, the abstract syntactic tree preprocessing, and the ground-truth edit sequence generation?
```

**Comment by LittleYUYU** [comment]
Hi @chontipan, sorry about the late reply! 

We have updated the README with suggestions on applying the model to other PLs (https://github.com/neulab/incremental_tree_edit#4-faq). We have also refactored part of the ASDL implementation accordingly. Please make sure you pull down the latest code.

To your other questions:
Q2: We do not have the code for converting the raw C# code to the AST in the GHE dataset. This is provided by the Graph2Tree paper (https://arxiv.org/pdf/1810.13337.pdf); please check out their released code for this part. However, since you are using the model for your own PL, I guess this code may not be very necessary. As we discuss in [README 4.1](https://github.com/neulab/incremental_tree_edit#41-applications-to-other-languages), the [TranX](https://github.com/pcyin/tranx) library could be useful as it includes ASDL for some other languages.

Q3: The generation of the target edit sequence has been included when you run the experiments following our instruction. It is language-agnostic, meaning that once you implement the ASDL for your own PL, by running the experiments you will collect the target edit sequences for your case. You can also do a sanity check by writing a [`demo_edits.py`](https://github.com/neulab/incremental_tree_edit/blob/master/asdl/lang/csharp/demo_edits.py#L60) script.

Hopefully these have addressed your concerns. Please let us know if you have more questions!

**Comment by chontipan** [comment]
Thanks!
